### ISSUE TITLE
Some packages (e.g. msmbuilder) are not being built by jenkins

### ISSUE THREAD

**Issue by jchodera** [omnia-md/conda-recipes#82] opened 2015-01-09 19:58 UTC
Some packages---notably, `msmbuilder`---are not being built by jenkins.

No information about them appears in the console output:
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/16/console

Not sure why this is.  Debugging.

**Comment by rmcgibbo** [comment] 2015-01-09 20:07
Not sure if this is related, but the msmbuilder recipe is a little weird in that it's just pulling the master branch from github. I'm going to do a proper release.

**Comment by rmcgibbo** [comment] 2015-01-09 22:48
@jchodera the issue looks to me like the dependency resolution in conda isn't working correctly. Can you try changing the jenkins configuration script to simply run `conda-build-all` twice. I think this will help, without a real loss of speed, since it'll skip files that have already been built.

**Comment by rmcgibbo** [comment] 2015-01-09 23:08
I can reproduce this on my machine now. I think I see the issue. Looking into it.

**Comment by jchodera** [comment] 2015-01-10 01:12
> Can you try changing the jenkins configuration script to simply run conda-build-all twice. I think this will help, without a real loss of speed, since it'll skip files that have already been built.

Done.  Jenkins `osx` and `linux` builds restarted.

**Comment by rmcgibbo** [comment] 2015-01-10 03:47
This is fixed now. You can also disable the part of the config where it's running the conda-build-all script twice.

**Closed by rmcgibbo** 2015-01-10 03:47 UTC

**Comment by jchodera** [comment] 2015-01-10 05:07
> This is fixed now. You can also disable the part of the config where it's running the conda-build-all script twice.

Thanks!  I've just disabled this, so future jenkins builds will not try to build twice.
